<a href="https://colab.research.google.com/github/ma1huy0113/THDL/blob/main/THDL_Buoi01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
my_list = [1, 9, 15, 39]
print('python list: ', my_list)

my_numpy_array = np.array(my_list)
print('numpy array: ', my_numpy_array)

my_list

python list:  [1, 9, 15, 39]
numpy array:  [ 1  9 15 39]


[1, 9, 15, 39]

In [ ]:
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [ ]:
c = np.array([
    (1, 2, 3),
    (4, 5, 6),
])
print(c)
print(c.shape)
print(c.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
int64


In [ ]:
d = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]
])
print(d)
print(d.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)


In [ ]:
e = np.zeros((2, 2))
f = np.ones((3, 3))
print('Zero matrix: \n', e)
print('Ones matrix: \n', f)

Zero matrix: 
 [[0. 0.]
 [0. 0.]]
Ones matrix: 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
e = np.array([[1, 2, 3], [4, 5, 6]])
print(e)
print(e.shape)

f = e.reshape(3, 2)
print(f)

g = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]
])

print(g)
print(g.shape)
h = g.reshape(3, 4)
print('reshape (3, 4)\n', h)
j = g.reshape(3, 2, 2)
print('reshape (3, 2, 2)\n', j)
k = g.reshape(2, 3, 2)
print('reshape (2, 3, 2)\n', k)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[1 2]
 [3 4]
 [5 6]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)
reshape (3, 4)
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
reshape (3, 2, 2)
 [[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
reshape (2, 3, 2)
 [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [ ]:
e = np.array([[1, 2, 3], [4, 5, 6]])
f = e.flatten()
print(f)
g = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]
])
j = g.flatten()
print(j)


[1 2 3 4 5 6]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
f = np.array([1, 2, 3])
g = np.array([4, 5, 6])
h_stack = np.hstack((f, g))
print('Horizontal Append\n', h_stack)
v_stack = np.vstack((f, g))
print('Vertical Append\n', v_stack)

Horizontal Append
 [1 2 3 4 5 6]
Vertical Append
 [[1 2 3]
 [4 5 6]]


In [ ]:
a = np.random.randint(100, size = (5))
print('Random 1-D array\n', a)
b = np.random.randint(100, size = (3, 4))
print('Random 2-D array\n', b)
c = np.random.randint(100, size = (3, 4, 3))
print('Random 3-D array\n', c)

Random 1-D array
 [43 86  9 62 44]
Random 2-D array
 [[ 3 11 61 23]
 [56 95  9 28]
 [38 32 38 23]]
Random 3-D array
 [[[18 93 55]
  [27 43 86]
  [24 53 36]
  [ 9 99 87]]

 [[ 2 51 16]
  [10 59  4]
  [67 70 27]
  [98 70 42]]

 [[43 36 16]
  [44 99 75]
  [58 66 13]
  [34 68 87]]]


In [ ]:
a = np.random.rand(5)
print('Random 1-D array\n', a)
b = np.random.rand(3, 4)
print('Random 2-D array\n', b)
c = np.random.rand(3, 4, 3)
print('Random 3-D array\n', c)

Random 1-D array
 [0.88813281 0.67819599 0.64891213 0.43865442 0.25950941]
Random 2-D array
 [[0.79823506 0.72331932 0.58378725 0.48809739]
 [0.74375926 0.60051057 0.83703347 0.2317203 ]
 [0.1326979  0.50630371 0.1286507  0.69591148]]
Random 3-D array
 [[[0.8709806  0.94170773 0.5822337 ]
  [0.22915134 0.89274527 0.35298335]
  [0.83343813 0.98404555 0.28233023]
  [0.36972328 0.36628065 0.55353552]]

 [[0.44576448 0.028074   0.56946124]
  [0.455321   0.02325599 0.47374859]
  [0.67496034 0.26868328 0.87793688]
  [0.45003998 0.65096772 0.54300153]]

 [[0.27982004 0.88474784 0.67389174]
  [0.30484867 0.69153808 0.67050243]
  [0.68602288 0.61622226 0.8132285 ]
  [0.27537413 0.97250316 0.01005059]]]


In [ ]:
a = np.random.normal(5, 0.5, 10)
print(a)

[4.56480324 4.15544654 4.68538686 4.29006603 5.77796972 5.59513776
 4.44088158 4.85586653 5.4356926  4.62249705]


In [ ]:
a = np.random.choice([2, 4, 6, 8, 10, 12, 14, 16, 18, 20])
print(a)
b = np.random.choice([2, 4, 6, 8, 10, 12, 14, 16, 18, 20], size = (3, 5))
print(b)

4
[[ 8  2  8  4  6]
 [18  8 16  2 10]
 [18 12  8  2 16]]


In [ ]:
a = np.matrix(np.ones((5, 5)))
print('The matrix\n', a)
np.array(a)[2] = 2
print('Change value of third row with array\n', a)
np.asarray(a)[2] = 2
print('Change value of third row with asarray\n', a)

The matrix
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Change value of third row with array
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Change value of third row with asarray
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
a = np.arange(1, 20)
print(a)
b = np.arange(1, 20, 2)
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 1  3  5  7  9 11 13 15 17 19]


In [ ]:
a = np.linspace(1., 5., num = 10)
print(a)


[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [ ]:
a = np.array([(1, 2, 3), (4, 5, 6)])
print(a)
print('first row: ', a[0])
print('second row: ', a[1])

print('first column: ', a[:,0])
print('second column : ', a[:,1])
print('first two value of second row: ', a[1, :2])

[[1 2 3]
 [4 5 6]]
first row:  [1 2 3]
second row:  [4 5 6]
first column:  [1 4]
second column :  [2 5]
first two value of second row:  [4 5]


In [ ]:
import pandas as pd
a = pd.Series([1., 2., 3.])
print(a)
print('First value: ', a[0])
b = pd.Series([1., 2., 3.], index = ['a', 'b', 'c'])
print(b)
print('First value: ', b['a'])
calories = {"day1": 420, "day2": 380, "day3": 390}
myvar = pd.Series(calories)
print(myvar)

0    1.0
1    2.0
2    3.0
dtype: float64
First value:  1.0
a    1.0
b    2.0
c    3.0
dtype: float64
First value:  1.0
day1    420
day2    380
day3    390
dtype: int64


In [ ]:
#numpy-->pandas
h = np.array([[1, 2], [3, 4]])
df_h = pd.DataFrame(h)
print('DataFrame\n', df_h)
#pandas-->numpy

numpy_h = np.array(df_h)
print('Numpy array:\n', numpy_h )


DataFrame
    0  1
0  1  2
1  3  4
Numpy array:
 [[1 2]
 [3 4]]


In [ ]:
dic = {'Name': ['John', 'Smith'], 'Age': [30, 40]}
df_dic = pd.DataFrame(dic)
print(df_dic)

    Name  Age
0   John   30
1  Smith   40


In [ ]:
r = np.random.randn(20, 4)
df = pd.DataFrame(r, columns = ['so1', 'so2', 'so3', 'so4'])
print(df.head())

        so1       so2       so3       so4
0 -0.072345 -0.163894  1.333333  0.280388
1  0.345514 -0.430529  0.884706 -0.258332
2 -0.416430 -0.211190  0.252363 -0.229075
3  0.923525  0.257503  0.801627 -0.536689
4  0.439213 -0.616755 -0.150019 -0.058690


In [ ]:
r = np.random.randn(20, 4)
df = pd.DataFrame(r, columns = ['so1', 'so2', 'so3', 'so4'])
print(df.head()) #in 5 dong dau tien
#Chon 1 cot
print(df['so1'])
#Chon nhieu dong
print(df[0:3])
#Chon nhieu cot
print(df[['so1', 'so3']])
#Chon nhieu dong, nhieu cot
print(df.iloc[:3, :2])
#Xoa cot
df = df.drop(columns=['so1', 'so4'])
print(df)



        so1       so2       so3       so4
0 -1.035907  0.192096  0.089021  0.625619
1 -0.013331  1.188594 -0.109608 -1.256230
2 -1.344309  0.075574  1.050147  1.159868
3  0.317922 -1.440794  0.306019 -0.096284
4 -0.779720 -0.612425 -0.607010  0.859771
0    -1.035907
1    -0.013331
2    -1.344309
3     0.317922
4    -0.779720
5    -1.400086
6    -1.132099
7    -0.907718
8     0.887981
9    -0.708034
10    2.610933
11   -0.527494
12   -0.246999
13    0.719830
14    0.078768
15   -0.248802
16    1.341799
17   -0.117780
18    0.162751
19    0.338309
Name: so1, dtype: float64
        so1       so2       so3       so4
0 -1.035907  0.192096  0.089021  0.625619
1 -0.013331  1.188594 -0.109608 -1.256230
2 -1.344309  0.075574  1.050147  1.159868
         so1       so3
0  -1.035907  0.089021
1  -0.013331 -0.109608
2  -1.344309  1.050147
3   0.317922  0.306019
4  -0.779720 -0.607010
5  -1.400086 -0.872595
6  -1.132099 -0.218083
7  -0.907718 -0.684599
8   0.887981  0.295192
9  -0.708034 -0.484657
1

In [ ]:
df1 = pd.DataFrame({
    'Name': ['John', 'Smith', 'Paul'],
    'Age': [25, 30, 50]
  }, index = [0, 1, 2])
df2 = pd.DataFrame({
    'Name': ['Adam', 'Smith'],
    'Age': [26, 11]
  }, index = [3, 4])
df_concat = pd.concat([df1, df2])
print('Concate two DataFrame\n', df_concat)
#Xoa gia tri o cot name trung nhau
df_drop = df_concat.drop_duplicates('Name')
print('Drop duplicates values in DataFrame\n', df_drop)
#Sap xep theo cot
print('Sort values in DataFrame\n', df_concat.sort_values('Age'))
#Doi ten cot
df_rename = df_concat.rename(columns={'Name': 'Surname', 'Age': 'Age_pupil'})
print('Rename columns in DataFrame\n', df_rename)
#

Concate two DataFrame
     Name  Age
0   John   25
1  Smith   30
2   Paul   50
3   Adam   26
4  Smith   11
Drop duplicates values in DataFrame
     Name  Age
0   John   25
1  Smith   30
2   Paul   50
3   Adam   26
Sort values in DataFrame
     Name  Age
4  Smith   11
0   John   25
3   Adam   26
1  Smith   30
2   Paul   50
Rename columns in DataFrame
   Surname  Age_pupil
0    John         25
1   Smith         30
2    Paul         50
3    Adam         26
4   Smith         11


In [3]:
import pandas as pd
dulieuxettuyen = pd.read_csv("https://raw.githubusercontent.com/huynhhoc/DataAnalystDeepLearning/main/Data/dulieuxettuyendaihoc.csv")
print (dulieuxettuyen.head(10))

   STT   T1   L1   H1   S1   V1   X1   D1   N1   T2  ...   X6   D6   N6  GT  \
0    1  7.2  7.3  6.3  7.3  7.0  7.9  7.3  5.5  8.4  ...  6.6  7.6  5.9   F   
1    2  5.4  3.9  3.9  4.0  5.4  5.4  5.3  2.8  6.3  ...  6.6  6.1  4.4   M   
2    3  5.6  6.8  7.2  7.5  4.3  7.4  5.8  3.2  5.0  ...  7.9  8.1  4.6   M   
3    4  6.6  6.4  5.3  6.9  5.4  7.3  6.4  5.8  5.1  ...  7.1  7.3  7.4   M   
4    5  6.0  5.0  6.0  7.3  6.5  7.7  7.9  6.1  5.4  ...  6.1  7.5  7.2   M   
5    6  9.3  7.6  7.9  8.6  7.0  7.3  7.7  7.9  9.6  ...  5.7  8.0  7.8   M   
6    7  2.8  3.9  5.5  6.9  5.0  7.3  4.6  5.2  4.4  ...  6.6  6.0  6.0   F   
7    8  8.3  6.0  7.6  5.1  7.5  4.7  5.8  7.2  6.7  ...  7.1  6.8  7.0   F   
8    9  6.5  6.3  7.6  6.0  5.5  7.1  6.3  5.0  7.3  ...  9.1  7.9  6.1   F   
9   10  7.3  5.9  4.7  7.1  6.7  7.9  6.7  7.7  8.0  ...  6.4  6.1  7.8   F   

   DT   KV   DH1   DH2   DH3  KT  
0 NaN  2NT  3.25  3.25  4.50  A1  
1 NaN    1  6.00  4.00  3.50   C  
2 NaN    1  5.00  6.75  4

In [ ]:
path = '/content/sample_data/Salart_Data.csv'
COLUMNS = ['YearsExperience', 'Salary']
df_csv = pd.read_csv(path, skipinitialspace = True, name = COLUMNS, index_col=False)
print(df_csv.head())
print(df_csv.shape)
df_csv1 = pd.read_csv(path, skipinitialspace = True, index_col=False)
print(df_csv1.head())
print(df_csv1.shape)
